#
# docker build -t samber/celery-exporter:3 -t samber/celery-exporter:latest -f Dockerfile.celery3 .
# docker run --rm -it --name celery-exporter -p 9000:9000 samber/celery-exporter:3 --broker redis://:aerty@my.redis.io:6379/0
#

FROM python:3.5

MAINTAINER Samuel BERTHE <contact@samuel-berthe.fr>

ENTRYPOINT ["python", "/celery_prometheus_exporter.py"]

COPY celery_prometheus_exporter.py /celery_prometheus_exporter.py

RUN pip install celery==3.1.25 redis prometheus_client
