#
# docker build -t samber/celery-exporter:4 -f Dockerfile.celery4 .
# docker run --rm -it --name celery-exporter -p 9000:9000 samber/celery-exporter:4 --broker redis://:aerty@my.redis.io:6379/0
#

FROM python:3.5

MAINTAINER Samuel BERTHE <contact@samuel-berthe.fr>

ENTRYPOINT ["python", "/celery_prometheus_exporter.py"]

COPY celery_prometheus_exporter.py /celery_prometheus_exporter.py

RUN pip install celery==4 redis prometheus_client==0.0.18

